### ISSUE TITLE
Swimat breaks identifiers

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#113] opened 2016-06-29 09:47 UTC
Hello. 
I've met a strange issue of Swimat breaking an identifier.
This is the 'minimal' code to replicate the issue, which I've extratced and obfuscated from a larger file.
Probably there are things that can be removed from it, but I've already deleted what I could.
If you format this file, the 3rd line from the end will be split into

``` swift
return dummy(abcdefghijklmnopqrstuvwxy
z)
```

If you make the identifier larger, it will be still be split before the last character. BUT originally, with the larger file, the identifier was split 5 characters from the end.
If I remove some mroe stuff from the file, then the split occurs before the `)`, that is, it's still wrong but compiles. This issue is not related to file size, but the specific outcome seems to be.

Test case:

``` swift
extension A1 {

    func obtainValue(value: String,
        done: String,
        completion: Result<String, NSError> -> Void)
    {
        guard let a = self.x.y?.z as? A2 else { fatalError("🔥 no") }

        log(.UI, "running...")

        a.b(c,
            d: ErrorType,
            f: { (g, h) in
                if let k = i {
                    log(.UI, "yes")

                    completion(.Success(k))
                } else if let error = error {
                    log(.UI, "yada yada yada yada yada yada yada \(error)")
                    completion(.Failure(error))
                } else {
                    fatalError("💥 no")
                }
        })
    }

    func b(completion: Result<(c: String, session: String), NSError> -> Void)
    {
        guard let x = self.y.z?.w as? W3,
            let c = d.e as? F else {
                fatalError("🔥 no")
        }

        a()
        b(c)

        d.e(f: { (g, h, error) in
            if let abcd = g, let h = h {
                log(.UI, "yada yada yada yada yada yada yada 🎉! ( abcd: \(abcd), h: \(h) )")
                completion(.Success((g: abcd, h: h)))
            } else if let error = error {
                completion(.Failure(error))
            } else {
                fatalError("🔥 no")
            }
        })
    }

    func c(completion: (Bool, NSError?) -> Void)
    {
        let d = {
            guard let e = self.f else {
                fatalError("🔥 no")
            }

            A.b(maxRetries) { x in
                self.a { (result) in
                    switch result {
                    case let .Success((_, g)):
                        s.f = g

                        self.e()
                        self.g()

                        self.h { result in
                            if case let .Failure(error) = result {
                                log(.UI, "yada yada yada yada yada yada yada \(error)")
                            }
                            completion(true, nil)
                        }
                    case let .Failure(error):
                        switch (error.domain, error.code) {
                        default:
                            log(.UI, "yada yada yada yada yada yada yada \(error)")

                            if !x() {
                                log(.UI,
                                    "yada yada yada yada yada yada yadan " +
                                        "yada yada yada yada yada yada yada")

                                self.k?.p()
                                self.p.x?.z.h = nil;

                                completion(false, error)
                            }
                        }
                    }
                }
            }
        }

    }

    func i(completion: Result<(), NSError> -> Void)
    {
        guard let a = self.x.y?.z as? A2 else { fatalError("🔥 no") }

        guard let a = self.x.y?.z as? A2 else { fatalError("🔥 no") }

        i.j(k: { (success, error) in
            if success {
                log(.UI, "yada yada yada yada yada yada yada 🎉")
                completion(.Success(()))
            } else if let error = error {
                log(.UI, "yada yada yada yada yada yada yada \(error)")
                completion(.Failure(error))
            } else {
                fatalError("💥 no")
            }
        })
    }
}

private enum E2 {
    static let abcdefghijklmnopqrstuvwxyz =
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456" +
        "ABCDEFG1234567890ABCDEFG1234567890ABCDEFG123456789"

    static func Abcdefghijklmnopqrstuvwxyz() -> NSData {
        return dummy(abcdefghijklmnopqrstuvwxyz)
    }
}
```

**Comment by Jintin** [comment] 2016-06-29 14:24
I can't reproduce this issue, could you reinstall and try again or use Swift version?

**Comment by Jintin** [comment] 2016-12-28 14:13
Did you face this issue in `extension` branch?
If don't, I would like to close it.
^^
Reopen or create a new one if you have any other or same issue.

**Closed as completed by Jintin** 2016-12-28 14:13 UTC
Labels: question
